FROM public.ecr.aws/lambda/python:3.12

RUN pip install --no-cache-dir \
    torch torchvision \
    --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir pillow boto3 psycopg2-binary

COPY lambda_function.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_function.lambda_handler"]

